### ISSUE TITLE
A new resource type for events needs to be supported

### ISSUE THREAD

**Issue by CANIS-NAU** [CANIS-NAU/QIResourceResilienceDB#77]
There are many recurring and one-time events offered in the community. 
The RRDB should be able to store these events. It should also automatically get rid of events that have already passed if they are not re-occurring.

**Comment by CANIS-NAU** [comment]
Hesitant to automatically remove items from the database, but we can adjust default filters to display only what is upcoming (with an optional filter)

Maybe a list of past events can be displayed to the admin and they can remove them.

**Comment by CANIS-NAU** [comment]
Good action item is to generate some mock-ups (we may already have some on Figma)

**Comment by JavadocMD** [comment]
Related search/filter UI changes: #78

**Comment by JavadocMD** [comment]
As Shelby noted in #78 comments: "People should be allowed to upload PDFs/files associated with events during resource submission."
